"""initial schema

Revision ID: 0dabbe4e492a
Revises: 
Create Date: 2026-08-09 12:27:51.475663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dabbe4e492a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_cik'), 'stocks', ['cik'], unique=False)
    op.create_index(op.f('ix_stocks_sector'), 'stocks', ['sector'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'source', name='uq_news_articles_url_source')
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_source'), 'news_articles', ['source'], unique=False)
    op.create_index(op.f('ix_news_articles_ticker_id'), 'news_articles', ['ticker_id'], unique=False)
    op.create_index('ix_news_articles_ticker_published', 'news_articles', ['ticker_id', 'published_at'], unique=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'price_date', name='uq_stock_prices_ticker_date')
    )
    op.create_index(op.f('ix_stock_prices_price_date'), 'stock_prices', ['price_date'], unique=False)
    op.create_index('ix_stock_prices_ticker_date_desc', 'stock_prices', ['ticker_id', 'price_date'], unique=False)
    op.create_index(op.f('ix_stock_prices_ticker_id'), 'stock_prices', ['ticker_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('rationale', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_executed_at'), 'trades', ['executed_at'], unique=False)
    op.create_index('ix_trades_portfolio_executed', 'trades', ['portfolio_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_trades_portfolio_id'), 'trades', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_trades_ticker_id'), 'trades', ['ticker_id'], unique=False)
    op.create_table('user_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_alerts_is_active'), 'user_alerts', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_alerts_ticker_id'), 'user_alerts', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_user_alerts_user_id'), 'user_alerts', ['user_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['user_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_id', 'article_id', name='uq_alert_history_alert_article')
    )
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_history_article_id'), 'alert_history', ['article_id'], unique=False)
    op.create_index(op.f('ix_alert_history_triggered_at'), 'alert_history', ['triggered_at'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_confidence', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', name='uq_sentiment_scores_article')
    )
    op.create_index(op.f('ix_sentiment_scores_article_id'), 'sentiment_scores', ['article_id'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_event_type'), 'sentiment_scores', ['event_type'], unique=False)
    op.create_index(op.f('ix_sentiment_scores_sentiment'), 'sentiment_scores', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_scores_sentiment'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_event_type'), table_name='sentiment_scores')
    op.drop_index(op.f('ix_sentiment_scores_article_id'), table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index(op.f('ix_alert_history_triggered_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_article_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_user_alerts_user_id'), table_name='user_alerts')
    op.drop_index(op.f('ix_user_alerts_ticker_id'), table_name='user_alerts')
    op.drop_index(op.f('ix_user_alerts_is_active'), table_name='user_alerts')
    op.drop_table('user_alerts')
    op.drop_index(op.f('ix_trades_ticker_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_portfolio_id'), table_name='trades')
    op.drop_index('ix_trades_portfolio_executed', table_name='trades')
    op.drop_index(op.f('ix_trades_executed_at'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_stock_prices_ticker_id'), table_name='stock_prices')
    op.drop_index('ix_stock_prices_ticker_date_desc', table_name='stock_prices')
    op.drop_index(op.f('ix_stock_prices_price_date'), table_name='stock_prices')
    op.drop_table('stock_prices')
    op.drop_index('ix_news_articles_ticker_published', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_ticker_id'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_sector'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_cik'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
