"""add market metadata to stocks

Revision ID: 3e9022270db3
Revises: 0dabbe4e492a
Create Date: 2026-08-09 14:33:35.084802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.services import markets


# revision identifiers, used by Alembic.
revision: str = '3e9022270db3'
down_revision: Union[str, Sequence[str], None] = '0dabbe4e492a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('mic', sa.String(length=8), nullable=True))
    op.add_column('stocks', sa.Column('region', sa.String(length=16), nullable=True))
    op.add_column('stocks', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('stocks', sa.Column('currency', sa.String(length=3), nullable=True))
    with op.batch_alter_table("stocks") as batch:
        batch.alter_column(
            "ticker",
            existing_type=sa.VARCHAR(length=16),
            type_=sa.String(length=24),
            existing_nullable=False,
        )
        batch.alter_column(
            "exchange",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=64),
            existing_nullable=True,
        )
    op.create_index(op.f('ix_stocks_country'), 'stocks', ['country'], unique=False)
    op.create_index(op.f('ix_stocks_mic'), 'stocks', ['mic'], unique=False)
    op.create_index(op.f('ix_stocks_region'), 'stocks', ['region'], unique=False)
    # Backfill the new columns for rows that already exist: without this an
    # established database keeps NULL region/mic/currency and every new
    # region filter silently returns nothing.
    connection = op.get_bind()
    stocks = sa.table(
        "stocks",
        sa.column("id", sa.Integer),
        sa.column("ticker", sa.String),
        sa.column("mic", sa.String),
        sa.column("region", sa.String),
        sa.column("country", sa.String),
        sa.column("currency", sa.String),
    )
    for row in connection.execute(sa.select(stocks.c.id, stocks.c.ticker)).all():
        market = markets.resolve(row.ticker)
        connection.execute(
            stocks.update()
            .where(stocks.c.id == row.id)
            .values(
                mic=market.mic,
                region=market.region,
                country=market.country,
                currency=market.currency,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_region'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_mic'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_country'), table_name='stocks')
    with op.batch_alter_table("stocks") as batch:
        batch.alter_column(
            "exchange",
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=32),
            existing_nullable=True,
        )
        batch.alter_column(
            "ticker",
            existing_type=sa.String(length=24),
            type_=sa.VARCHAR(length=16),
            existing_nullable=False,
        )
    op.drop_column('stocks', 'currency')
    op.drop_column('stocks', 'country')
    op.drop_column('stocks', 'region')
    op.drop_column('stocks', 'mic')
    # ### end Alembic commands ###
